### ISSUE TITLE
Data Insight Improvements

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10204]
**Context**
The list of task below represents the improvements for the data insight.

Bugs (Release 1.0):
- [x] #10571
- [x] Exclude Traffic for the owner [Ingestion] https://github.com/open-metadata/OpenMetadata/pull/10574

Metrics (new/improvements):
- [x] Data Assets by Team Breakdown 
- [x] Description coverage -> allows a looser definition for tables
- [ ] Most viewed -> allow to view more than 10 + export + sortable
- [ ] Most Viewed Data Assets -> Add ability to filter by team + add description coverage column. More globally filters should act the same on all elements
- [x] Test coverage by entities
- [x] Most used entities -> by usage (from usage metrics)

Filters (new/improvements):
- [ ] Page views by Owner/Tier/Team
- [ ] Add No Tier Value in the tier filter

**Comment by harshach** [comment]
@ulixius9 lets see if we can ship these via new Data Insights as default dashboards
