### ISSUE TITLE
Databricks all Issues List

### ISSUE THREAD

**Issue by MilanBariya** [open-metadata/OpenMetadata#10535]
- [x] Databricks ingestion fails when catalog name contain "catalog" word.
- [x] Some Tables are not getting ingested in Databricks #10420
- [x] Databricks metadata ingestion job fails due not waiting engouth time to the cluster be ready #9639
- [x] DatabricksPipeline not working properly #10003
