### ISSUE TITLE
Add support to Data Model entity for Dashboards

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#10584]
**Is your feature request related to a problem? Please describe.**
We need support to get the Data Models on what the Dashboards are based into a separate Entity. For this first iteration, we are going to implement it for Tableau.

For Tableau, we plan to get each sheet object model and display it as an entity of the dashboards. We will use this new entity to get the lineage between database services databases and dashboards.

**Tasks**
- [x] Create JSON schema, repository, and endpoint for the data model entity. @nahuelverdugo  https://github.com/open-metadata/OpenMetadata/pull/10636
- [x] Display Data Model Entity in UI. @Ashish8689 
- [x] Add DataModel Filter under Dashboard Entity in explore page in UI. @aniketkatkar97 
- [x] Ingest Tableau Data Model for dashboards. https://github.com/open-metadata/OpenMetadata/pull/10872
- [x] Ingest Lineage for Tableau dashboards considering data model entity. https://github.com/open-metadata/OpenMetadata/pull/10923
- [x] Update ES indexes @nahuelverdugo https://github.com/open-metadata/OpenMetadata/pull/10851
- [x] The Metadata Ingestion Pipeline should support the following:
    - [x] Toggle to ingest or not the data models
    - [x] Data model filter pattern
- [x] Add support for column level lineage between dashboadDataModel <> Table. This is required in the backend  https://github.com/open-metadata/OpenMetadata/pull/11489

**Comment by pmbrull** [comment]
We'll do the col-level lineage in 1.1, as it requires some changes in the backend
