### ISSUE TITLE
Data Observability - Separate Alerts from Notification

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#10757]
Currently, we are mixing Alerts and Notifications via the same mechanism. However, the mechanism might be the same for Notifications and Alerts in the backend the usability from the UI suffers. 

Changes Proposed:
1. Rename Alerts under the Notifications section to be Notifications
2. Notifications should have the same Trigger mechanism as selecting a Resource
3. Filter By options will have 
     1. EventType
     2. Owner
     3. FQN
     4. UpdatedBY
     5. Task is added
     6. Tasks is deleted
     7. Task is closed

4. Add a new Section on the Settings page -> "Data Observability."
    1. Add Alerts
    2. In Alerts, We will have the following Trigger options
       2.1.  Tables, Topics, Database etc..
            2.1.1. Schema Change (column added/deleted, type changed,...)
            2.1.2. Ownership
            2.1.3 Tags
            2.1.4 Deleted
            2.1.5 Pipeline Status
            2.1.6 Test Case Result
      2.2 Allow Branch conditions or multiple conditions
           2.2.1 match on FQN and test Result
           2.2.2 match on FQN test result etc..
    3. Destination
    

Todos

- [ ] https://github.com/open-metadata/OpenMetadata/issues/10428
- [ ] https://github.com/open-metadata/OpenMetadata/issues/12505
- [ ] https://github.com/open-metadata/OpenMetadata/issues/10319
- [ ] https://github.com/open-metadata/OpenMetadata/issues/9874

**Comment by harshach** [comment]
@mohityadav766 @Sachin-chaurasiya pushing this to 1.3

**Comment by harshach** [comment]
Ex:

Send me alerts on all of my following assets when a schema changes or a test fails
Send me alerts on all changes to my owned data assets
Send alerts when my test suite has one or more failures
Separating general purpose alerts vs data observability alerts

This epic will also fix the current issues that are propping up in our alert system

**Comment by harshach** [comment]
@mohityadav766 @chirag-madlani @aniketkatkar97 what is remaining here to close it out?

**Comment by aniketkatkar97** [comment]
@harshach the unit tests are remaining here and a minor bug from the backend side

**Comment by aniketkatkar97** [comment]
Feature completed with #14969
