### ISSUE TITLE
Test Connection Improvements

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#10774]
Ingestion / Backend:

- [x] Use PATCH for the response on the ingestion side to update steps and status (or a separate endpoint to manage updating responses only) #10897
- ~~If the test connection has a serviceName, update the service `lastTestConnection` status with the results and showcase that on the UI (P1)~~ Moved to 1.2 https://github.com/open-metadata/OpenMetadata/issues/11908
- [x] Every server start should try to createOrUpdate the test connection definition, or clean them and ingest in full. This will make our lives easier going forward if we modify anything in the description etc
- [x] Short-circuit test connection if the first "access" check fails. This should validate networking and creds and stop the processing if cannot be accomplished. #10913
    - Add a `shortCircuit` flag in the step so that we know on the ingestion side that we need to stop the execution
- [x] Deprecate the old `test_connection` endpoint: https://github.com/open-metadata/OpenMetadata/pull/10798
- [x] Improve error messaging, content and style. We are throwing errors that are too technical. We should log the exceptions and tracebacks, and wrap the error in something that can be properly digestible by the user #10913
    ![image](https://user-images.githubusercontent.com/35870520/229024076-70743eac-e840-47e6-88c1-b230318a250b.png)
- [x] Add some logging in the process #10913
- [x] Looker: Validate instance version is compatible with [SDK](https://cloud.google.com/looker/docs/api-sdk) version as a test connection step

---
## Improve test connection cleanup/deletion: 

2 scenarios where test connection workflows are not being deleted:  

#11912 

1. [x] We are running the test connection and refresh/leave the page. Then the UI loses track of the operation and does not issue the deletion at the end
2. [x] If the test connection dies at the very beginning in Airflow, then the UI issued the POST, but as it does not expect any results back, it does not run the DELETE

---
UI:
@devyani-kaushik , will need your help on the design.
- [x] Once the UI receives the test connection result, it should DELETE the workflow. https://github.com/open-metadata/OpenMetadata/pull/10822
  - Note that now the UI does not allow to click multiple times on test connection until the workflow is finished.
- [ ] 1.2 - Localization: Have `locale` keys for the test definition steps for cleaner naming. `Get Views` instead of `GetViews`, and handle translations. Same for descriptions: `GetViews.description` . Refer to [this](https://github.com/open-metadata/OpenMetadata/tree/main/openmetadata-service/src/main/resources/json/data/testConnections) for adding a localization structure 
- [x] Show ingestion test result summary. We can have 3 main scenarios: https://github.com/open-metadata/OpenMetadata/pull/11010
  1. Everything passed, we can say "Test connection ran successfully", (easy to improve the wording)
  2. A mandatory step(s) failed: "Test connection failed, please validate your connection and permissions for the failed steps".
  3. All mandatory steps passed, but some non-mandatory steps failed. 
  Show non-mandatory failed tests as a yellow warning instead of a red cross. The banner could say: "Test connection partially successful: Some steps had failures, we will only ingest partial metadata".
- [x] Styling and progress (from https://github.com/open-metadata/OpenMetadata/pull/10660#issuecomment-1485465561) https://github.com/open-metadata/OpenMetadata/pull/11010
- [x] We cannot get the details again once the test connection is running  https://github.com/open-metadata/OpenMetadata/pull/10819
    <img width="672" alt="image" src="https://user-images.githubusercontent.com/35870520/228210661-acd26e22-2a4b-48a1-ae69-7050e51a4fc5.png">
- [x] In case of test connection definition API failed response, nothing is shown in the test connection modal. https://github.com/open-metadata/OpenMetadata/pull/10885

https://user-images.githubusercontent.com/51777795/228542766-40fd8093-9770-4f3f-b999-9d6c7016ef66.mov

**Comment by harshach** [comment]
More feedback here https://github.com/open-metadata/OpenMetadata/pull/10660#issuecomment-1485465561 cc @Sachin-chaurasiya @chirag-madlani

**Comment by Sachin-chaurasiya** [comment]
> More feedback here [#10660 (comment)](https://github.com/open-metadata/OpenMetadata/pull/10660#issuecomment-1485465561) cc @Sachin-chaurasiya @chirag-madlani

Thanks @harshach, we will check that.
