### ISSUE TITLE
UI - epic for 1.1 backlogs

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#11154]
- [ ] Similar signup flow for Basic auth too
- [x] Product tours
- [x] Support menu improvement on the AppBar
- [x] First-time user experience on the landing page (Currently blank page with few Filters)
- [x] Welcome message screen for first time user
  - New design @deviyani -> show only onetime for logged in user
  - Depending on persona provide a tour -> future
  - Specific tour as per logedin user role -> future

- [ ] [DataModel does not have the UI lineage editor enabled](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1506912066)
- [ ] [Pagination support for Services, CustomProperties & TestSuites](https://github.com/open-metadata/OpenMetadata/issues/10543#issuecomment-1465692039)
- [ ] When you search for a team in Add user page, the entire hierarchy of a team is shown in the search suggestions. This should be the same when setting teams in User profile page. It can also be the same when setting the owner on the entity details page. We need to look at all the places where we are suggesting teams and follow the same search suggestion on Add user page. cc @harshach @chirag-madlani
- [ ]  Organization name not available while editing Teams in user profile page --> @chirag-madlani 
![image](https://user-images.githubusercontent.com/12962843/233410204-0e008099-49c9-442c-8f1b-c456cbc52c7a.png)

**Comment by harshach** [comment]
- [ ] Expand all the teams by default. Add "Collapse/Expand" similar to Glossary 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/38649/233815044-487961cb-533e-475b-95e7-741bcd6c4eea.png">

**Comment by harshach** [comment]
- [ ] There needs to be some separation between Description and its immediate children . @devyani-kaushik pointed this out in our multiple discussions
<img width="1509" alt="image" src="https://user-images.githubusercontent.com/38649/233861381-efec2555-8ccf-402b-a1d5-94540925c423.png">

**Comment by harshach** [comment]
- [ ] Description should have a fixed width can't go down to one letter per line. We should add scroll bars instead of going to this level of adjustment 
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/38649/234123490-75ae618c-fca3-4027-aa48-2f6275fe8272.png">

**Comment by Ashish8689** [comment]
- [ ]  Need to change the Label for Tags to `--` when for Non-admin case when no tags are there
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/66266464/234295592-3fbc718d-7730-4009-85fc-4e81b4848002.png">

**Comment by sureshms** [comment]
- [ ] Tags don't have anything on the left panel. We should add similar to Glossaries, filtering by Classifications.
<img width="1398" alt="image" src="https://user-images.githubusercontent.com/1417689/234378856-cb2f88df-2727-4f78-8e8a-692c5d76a914.png">

**Comment by sureshms** [comment]
- [ ] Side panel can't show the entire breadcrumb for long names. Maybe we should not show breadcrumb in the preview. cc @harshach 
<img width="411" alt="image" src="https://user-images.githubusercontent.com/1417689/234380020-7dc1aeda-1412-4256-ab3f-1a6b7f739713.png">

**Comment by sureshms** [comment]
- [ ] Not sure why there is a shadow before the Action column: 
<img width="1609" alt="image" src="https://user-images.githubusercontent.com/1417689/234386315-e247e852-98cc-4e36-8885-fa69dffc4e16.png">
- [ ] TestSuite can't be deleted and throws an error "testSuite is not empty" even if all the tests under it are deleted.

**Comment by sureshms** [comment]
- [ ] In the 1.0 released splash, instead of Try Now! (which sounds like try the new release, typically used in upgrading software) we should say, "See What's New!"
<img width="282" alt="image" src="https://user-images.githubusercontent.com/1417689/234391774-25ad69d2-8567-4be0-8333-4970d95037e2.png">

**Comment by sureshms** [comment]
- [ ] Add a full stop after "No result found" 
<img width="485" alt="image" src="https://user-images.githubusercontent.com/1417689/234436951-940edf19-b346-4242-8400-64a0781868f2.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ]  Handle word break in teams page. --> @karanh37 

https://github.com/open-metadata/OpenMetadata/issues/10503#issuecomment-1501611871

**Comment by Sachin-chaurasiya** [comment]
- [ ] Without passing the required details, click  on the test connection button, it's giving error from airflow, but it should first check required field for connection. 

@Sachin-chaurasiya 

https://user-images.githubusercontent.com/52292922/233024217-8d00c081-fbb1-4fab-a4bf-36ab8e6bf24b.mov

**Comment by Sachin-chaurasiya** [comment]
@karanh37 
- [ ] Rename the glossary term. In the version we don't clearly say what the name was before and after and no diff is shown 
<img width="302" alt="image" src="https://user-images.githubusercontent.com/1417689/233644383-25c2329d-f7e6-4928-967b-359a074e6d6c.png">

- [ ] When a glossary term is moved, we don't show in version history what it's previous parent was and no diff is shown 
<img width="308" alt="image" src="https://user-images.githubusercontent.com/1417689/233644704-70fd6836-a296-46f3-89c4-3ba3bd8df687.png">

**Comment by Sachin-chaurasiya** [comment]
- [ ] Show tags hierarchically. Instead of showing multiple options with PII and the corresponding tag, show PII once and all the tags that belong to it grouped under it. 
<img width="497" alt="image" src="https://user-images.githubusercontent.com/1417689/233647783-b4fcc6d4-dbfe-4693-9ebb-8a0f53303d73.png">

**Comment by Sachin-chaurasiya** [comment]
Tested on the final 1.0.0:

- [ ] This was already added and marked as solved, but the issue persists. If a column has `dataType` but not `dataTypeDisplay`, we don't show it

![image](https://user-images.githubusercontent.com/35870520/234360686-84559050-3b1f-4561-bb1e-89296fd41b5e.png)

- [ ] Custom storage does not have an icon

![image](https://user-images.githubusercontent.com/35870520/234360760-c82e1f39-1ad9-4dc3-a103-37e2a10230f1.png)

**Comment by Sachin-chaurasiya** [comment]
- [ ] In data asset details page, we should limit the number of tags displayed to a smaller number and include a text "X more" which users can click to see all the tags. Also we should align the announcements in the space below versions and follow. --> @aniketkatkar97 
<img width="1696" alt="image" src="https://user-images.githubusercontent.com/1417689/233808770-26ba7f95-0a02-4d95-918a-1f624047fc13.png">

**Comment by Sachin-chaurasiya** [comment]
@ShaileshParmar11 
- [ ] Add random text in a query and add it. It succeeds without throwing any errors. We should validate SQL query. -> moving to 1.1 required research on our end
- [ ] For a query `Query used by other tables` can't be edited. -> **moving to 1.1**

**Comment by Sachin-chaurasiya** [comment]
Placeholder Graphics - @chirag-madlani  @Ashish8689 
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=13876%3A30765&t=F6pXxoL3NYanbeYN-1

**Comment by harshach** [comment]
- [ ] Charts and Insights where we have dashboard kind of styling we are displaying no data found like this . This doesn't look right. Lets revert back to older method for charts/dashboards
![image](https://user-images.githubusercontent.com/38649/234765029-1b795835-9b73-4570-a72a-b3470ea404c3.png)

**Comment by ShaileshParmar11** [comment]
- [ ] Add a tooltip to notify about not having access to the pipeline action button

https://user-images.githubusercontent.com/71748675/234776201-8b2802ab-1c11-447a-b776-bc0538b81fe4.mov

**Comment by ulixius9** [comment]
- [ ] If i just be idle on logs screen for few seconds the logs disappear

https://user-images.githubusercontent.com/39544459/234782502-b3cf65ce-7aa8-4b3d-87ba-cc49f688c40d.mov

**Comment by ulixius9** [comment]
- [ ] space missing for "the Metadata Ingestion"

![image](https://user-images.githubusercontent.com/39544459/234784819-c5a98416-9338-4004-a003-e372d52e2b2a.png)

**Comment by ShaileshParmar11** [comment]
- [ ] Even after having edit description permission, the edit icon is not visible on the test suite details page (non-admin view)
<img width="1624" alt="image" src="https://user-images.githubusercontent.com/71748675/234814620-04a03b0f-2b73-48ea-a743-90b6e72d04a2.png">

**Comment by harshach** [comment]
- [ ] versions diff showing markdown 
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/38649/234912454-993df841-1f45-48aa-98b1-644f013574ae.png">

**Comment by harshach** [comment]
- [ ] versions diff - Regression - the deleted term is not shown properly. We used to show with strikethrough cc @chirag-madlani 
<img width="1659" alt="image" src="https://user-images.githubusercontent.com/38649/234912947-c683c0dc-5610-4aca-bc6f-33ff35bff36d.png">

**Comment by sureshms** [comment]
- [ ] All icons in the breadcrumb should have a tooltip to describe what type of a service it is. 
<img width="203" alt="image" src="https://user-images.githubusercontent.com/1417689/234950630-571d457c-3d3e-4627-8478-410d58d91c9d.png">

**Comment by devyani-kaushik** [comment]
- [ ] fields are overlapping 
- [ ] After saving, While loading we show "Add New" placeholder, maybe we should show simple skeleton loader 

https://user-images.githubusercontent.com/103238069/235849253-0a695bb3-9065-4ca2-8c9b-a636f17bc163.mov

**Comment by sureshms** [comment]
- [ ] On first-time login, if the user clicks and moves to another page, if he comes to the landing page both welcome splash and what's new splash disappear. They should continue to appear until the user clicks x on those panels to get rid of them.

**Comment by ShaileshParmar11** [comment]
Moving from 1.0.1 to 1.1
- [x] this field should use the same type of owner field where we show users and teams separately. Here we are putting them together - [original issue](https://github.com/open-metadata/OpenMetadata/issues/11407#issuecomment-1536711539)
<img width="865" alt="image" src="https://user-images.githubusercontent.com/38649/236557262-264f8d4f-20f9-404f-a564-3ec826884180.png">
as decided [here](https://github.com/open-metadata/OpenMetadata/pull/11482#issuecomment-1538692414) we need same behavior of the owner widget here
- [ ] same here typing @ should open the same panel as entity owner panel -> [original](https://github.com/open-metadata/OpenMetadata/issues/11407#issuecomment-1536715082) 
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/38649/236557802-cfadd1c7-85df-4f8c-ae0c-9cb59e76833f.png">

**Comment by ShaileshParmar11** [comment]
- [ ] need to have consistent color for edit icon @devyani-kaushik 
![image](https://user-images.githubusercontent.com/71748675/237026329-90ec99cb-9a7a-478d-9d4b-610880b3456b.png)
