### ISSUE TITLE
UI - add version pages for missing entities

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#11221]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Describe the bug**

- [x] The version page for Topic details is not showing all the details refer screenshot:

![image](https://user-images.githubusercontent.com/12962843/233846421-9fff38c2-aeb0-428a-8ef0-5fb4edc13217.png)

- [x] Topic config should show all the config available from backend instead filter it out based on the Top bar available

**To Reproduce**

1. Refer version page for any topic and check history

**Expected behavior**

- It should show version details for all others tabs as well

**Version:**
 - Python version:
 - OpenMetadata version: [e.g. 0.8]
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`]

**Additional context**

**Comment by chirag-madlani** [comment]
Let's revisit all the version components to make sure it's aligned with all the new features

- [ ] Table
- [ ] Topic
- [ ] Dashboards
- [ ] Glossary
- [ ] Pipeline
- [ ] mlModel
- [ ] Container
- [ ] DataModel

**Comment by Sachin-chaurasiya** [comment]
> Let's revisit all the version components to make sure it's aligned with all the new features
> 
> * [ ]  Table
> * [ ]  Topic
> * [ ]  Dashboards
> * [ ]  Glossary
> * [ ]  Pipeline
> * [ ]  mlModel
> * [ ]  Container
> * [ ]  DataModel

All these entities should have the following things as well
- Tasks
- Announcements
- Conversations

**Comment by aniketkatkar97** [comment]
Version pages to be added-

- [ ] Classifications and tags
- [ ] Team
- [ ] User
- [ ] Role
- [ ] Policy
- [ ] Services
- [ ] Custom Attributes
- [ ] Activity Feeds
- [ ] Alerts

**Comment by aniketkatkar97** [comment]
I will be handling the code refactoring for service, database and database schema details pages while adding version pages to the same.
cc: @chirag-madlani
