### ISSUE TITLE
UI Form Refactoring and Improvements

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#11358]
The goal of this epic is to improve the form we have in the UI and use the Antd form everywhere. 

- Better validation and validation should be aligned with JSON schema
- Form state should be managed by the form itself, we should not have the local states
- We should use the Form props over our own props

List of forms to be worked on

- [x] Signup
- [x] SignIn
- [x] Forget Password
- [x] Team
- [x] User
- [x] Roles
- [x] Policy
- [x] Rule
- [x] Service
    - [x] Configure Service Form  https://github.com/open-metadata/OpenMetadata/pull/11734
    - [x] Database
    - [x] Dashboard
    - [x] Pipeline
    - [x] Messaging
    - [x] Ml Models
    - [x] Metadata
    - [x] Storage
- [x] Ingestion ( Workflow )
- [x] Activity Feeds
- [x] Alerts
- [x] Custom Attributes  #11656
    - [x] Tables
    - [x] Topics
    - [x] Pipelines
    - [x] Dashboards
    - [x] Ml Models
    - [x] Containers
- [x] Search index Pipelines
- [x] Data Insight Pipelines
- [x] Email Configuration 
- [ ] Bots
- [x] Test Suites
- [x] Table test
- [x] Column Test
- [x] KPIs
- [x] Glossary https://github.com/open-metadata/OpenMetadata/pull/11780
- [x] Glossary Term https://github.com/open-metadata/OpenMetadata/pull/11780
- [x] Classification https://github.com/open-metadata/OpenMetadata/pull/11706
    - [x] Tags

**Comment by harshach** [comment]
@Sachin-chaurasiya where are we with this? and what are the blockers?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya where are we with this? and what are the blockers?

Hello @harshach , the major part of aligning entity names with json schema is done, now minor improvements and refactoring is pending, will take care of it in 1.2.

**Comment by harshach** [comment]
@Sachin-chaurasiya what is remaining here?

**Comment by Sachin-chaurasiya** [comment]
Closing this issue as we are using the antd Form everywhere now and only bots one is pending which will be handled in https://github.com/open-metadata/OpenMetadata/issues/12882
