### ISSUE TITLE
UI - Cypress Test Coverage

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12452]
**Is your feature request related to a problem? Please describe.**
This EPIC is to track all the cypress tests for the UI

**Create Roles**
We need to cover the below behavioral tests for all the roles, cypress tests should run as 
1. Admin
2. Data Steward
3. Data Consumer
5. Create Role with -> ViewBasic
6. Create Role with -> ViewBasic, ViewSampleData, ViewQueries
7. Create Role With -> ViewBasic, ViewSampleData, ViewQueries, ViewTests 
8. Create Role With -> ViewBasic, ViewSampleData, ViewQueries, EditQueries 
9. Create Role With -> ViewBasic, View SampleData, ViewQueries, EditQueries, EditTests
10. Create Role With -> ViewBasic, View SampleData, ViewQueries, EditQueries, EditTests, EditDisplayName

**Landing Page**

Test this for above roles 1 - 5

- [x] Landing page must show activity Feed
- [x] User should be able to reply on the activity feed and  add emojis
- [x] User should be able to tag other users or other assets in the comments
- [x] Create a thread that mentions the same user in the reply, switch to mentions, and check if that thread exists or not
- [x] Create a task and assign it to the logged-in user and check if those tasks appear in the tasks section or not
- [ ] Search for an entity and assign a team the user belongs to as the owner. Go back to the landing page? That particular asset should show up in the My Data panel. Do this for all entity types
- [ ] Search for an asset and assign ownership to the logged-in user. Return to the landing page, and that particular asset should appear in the My Data Panel. Do this for all entity types
- [x] Search for an asset and follow the asset. Go back to the landing page, and it should appear in the Following panel. Do this for all the entity types
- [x] Follow more than 20 assets. Check View All count. Click on View All, the page should show all 20 following
- [x] Own more than 20 assets of various types, check the My Data count, the page should show all the 20 assets
- [x]  Deploying a Search re-index pipeline
- [x]  Triggering search re-index
- [x]  Cypress for entity summary panel
- [x]  Refactor AddAndRemoveTierAndOwner spec to remove sample_data dependency to fix the dashboard related test fail

**Comment by karanh37** [comment]
- [ ] Drag & Drop for teams and glossary
