### ISSUE TITLE
Add support for SearchIndexes from ElasticSearch and OpenSearch

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12779]
**Is your feature request related to a problem? Please describe.**
Add support for collecting metadata from SearchIndexes in ElasticSearch and OpenSearch. 

**Describe the solution you'd like**

- [x] Add SearchServices with connections to ElasticSearch and OpenSearch
- [x] Add SearchIndexes APIs
- [x] Add SearchIndexes support for Search
- [x] Add SampleData for SearchIndexes
- [x] Add UI support for displaying SearchIndexes entity page and add Search Tab
- [ ] Add version page for Search Index entity
