### ISSUE TITLE
Support for Stored Procedures as another entity under Database Schema

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#12998]
**Is your feature request related to a problem? Please describe.**
Stored Procedures important entity in a database, many users are expressed interest in capturing metadata about stored procedures and potentially lineage

**Describe the solution you'd like**
We will be adding Stored Procedure as another entity with a parent container as the Database Schema.
There will be APIs under /api/v1/storedProcedures to capture the metadata about Stored Procedures

- [x] Backend APIs for Stored Procedures
- [x] Sample Data for Stored Procedures
- [x] UI support for Stored Procedures
- [x] Search support for Stored Procedures
- [x] Ingestion Support
- [x] Missing aggregation in search
- [ ] cypress for storedProcedure and data models

**Related issues**
- https://github.com/open-metadata/OpenMetadata/issues/12167

**Comment by asprdnv** [comment]
Hi, will we able to build pipelines and lineage based on stored procedures?

We call procedures in MSSQL Jobs – usually 1 step = 1 procedure

**Comment by pmbrull** [comment]
hi @asprdnv Stored Procedures are ingested under the Database Schema that they live in. Not sure if we'll have enough room to handle MSSQL for 1.2.0. If not, we'll add them in 1.2.1

**Comment by chuqbach** [comment]
Hi, how about Oracle Stored Procedure? Do you have any plan for it?

**Comment by nqvuong1998** [comment]
Hi @pmbrull ,  Do you have any plan to implement Stored Procedure for Oracle?

**Comment by ayush-shah** [comment]
@nqvuong1998 you can track the fix for the same from here: https://github.com/open-metadata/OpenMetadata/pull/14641
and the issue for it: https://github.com/open-metadata/OpenMetadata/issues/14630
