### ISSUE TITLE
Opinions about module ingestion

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#1331]
I'm collecting some opinions about the module ingestion. I'm rusty in Python development and it's possible that I'm missing some ideas here.

- [ ] We don't need requirements.txt (#1344)
- [ ] We could convert requirements-dev.txt and requirements-test.txt in plugins in setup.py. (#1344)
```
pip install -e '.[dev]'
pip install -e '.[test]'
```
- [ ] We should not pass credentials in the configuration file, in particular, the glue source should use the [AWS boto session](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/session.html#custom-session) to get the credentials from the different credential providers. (#1345)
- [ ] The integrations tests don't work on my machine. (probably #1339 and #1340)
- [ ] The unit tests and integrations tests should be included in the CI. (probably #1339 and #1340)
- [ ] We should include in the documentation how to configure Intellij for mixed development (Java and Python). (#1347)
- [ ] py310 doesn't work with the BigQuery connector. (#1346)
- [ ] we should use ```tox``` to test py38 and py39. (#1346)

**Comment by harshach** [comment]
Thanks @amiorin 
1. Makes sense. But most of the IDEs are dependent on requirements.txt so not sure if removing it would cause any issues. 
2. sounds good. we can update the docs
3. credentials can be passed as env vars , we parse those from the config files. The examples we have is for testing it out.  https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/config/common.py#L63 expandsvars does the work for us in reading the creds
4. @ayush-shah can you check why integration tests are not working. @akash-jain-10 can you start looking into making this as GitHub action
5. ^
6. we are using PyCharm. we should do the documentations around it cc @ayush-shah . I am not sure if anyone can use IntelliJ it would support both Python and Java. PyCharm being IntelliJ product.
7. @ayush-shah can you check any reason for python3.10 not working
8. +1 for tox. We need to line up in a release. 

cc @pmbrull

**Comment by pmbrull** [comment]
Thanks, @amiorin, @harshach,

- Ok to simplify requirements. At some point, we could even try to change the setup to other tools such as `poetry`, which already come with different helpers for the install and packaging. Also, as they provide a lock file, it is easier to use completely the same versioning snapshots.
- `expandvars` I believe can do the trick so far. It might be interesting to review the deployment process in a typical PROD environment where you want IaC.
- There is currently ongoing work on adapting the CI for python tests https://github.com/open-metadata/OpenMetadata/issues/1287#issuecomment-974862408

**Comment by amiorin** [comment]
> Thanks @amiorin
> 
> 1. Makes sense. But most of the IDEs are dependent on requirements.txt so not sure if removing it would cause any issues.
> 2. sounds good. we can update the docs
> 3. credentials can be passed as env vars , we parse those from the config files. The examples we have is for testing it out.  https://github.com/open-metadata/OpenMetadata/blob/main/ingestion/src/metadata/config/common.py#L63 expandsvars does the work for us in reading the creds

Credentials are rotated in EC2 instances with Instance Profile. We should stick to the credential provider chain because it doesn't stop our users from providing static credentials but it makes it possible to the more "enterprise" users to use rotation. I know of an example in [Java in Trino](https://github.com/trinodb/trino/blob/d90c1b793213509d34e0a6a345f441db2e7ee9b5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java#L938) but the same thing can be done in boto3 with a custom session.

> 4. @ayush-shah can you check why integration tests are not working. @akash-jain-10 can you start looking into making this as GitHub action
> 5. ^
> 6. we are using PyCharm. we should do the documentations around it cc @ayush-shah . I am not sure if anyone can use IntelliJ it would support both Python and Java. PyCharm being IntelliJ product.

IntelliJ supports both Python (by installing the plugin) and Java at the same time in the same project.
![image](https://user-images.githubusercontent.com/32617/142984861-452e56e9-2ebc-409d-b0ee-123fe3a77cae.png)

> 7. @ayush-shah can you check any reason for python3.10 not working
> 8. +1 for tox. We need to line up in a release.
> 
> cc @pmbrull

**Comment by amiorin** [comment]
> Thanks, @amiorin, @harshach,
> 
> * Ok to simplify requirements. At some point, we could even try to change the setup to other tools such as `poetry`, which already come with different helpers for the install and packaging. Also, as they provide a lock file, it is easier to use completely the same versioning snapshots.

The lock files would only work for direct dependencies, right?

**Comment by pmbrull** [comment]
@amiorin I think the lock file writes down all the dependencies in the project: https://python-poetry.org/docs/basic-usage/#installing-dependencies

**Comment by amiorin** [comment]
My setup with Apple Silicon
```sh
brew install pyenv
brew install pyenv-virtualenv
pyenv install 3.9.7
pyenv virtualenv 3.9.7 openmetadata
pyenv activate openmetadata
brew install openblas
brew install librdkafka
OPENBLAS="$(brew --prefix openblas)" pip install scipy
# similar thing for pip install confluent-kafka
pip install -e '.[all]'
```
Add the venv openmetadata to IntelliJ SDKs.
![image](https://user-images.githubusercontent.com/32617/142986664-6036c8d3-9907-4f69-a24f-5c7c43c74496.png)

1. Add the ingestion module
2. Mark src and test
![image](https://user-images.githubusercontent.com/32617/142986771-9c993f46-7b19-481f-91bd-ccfb84222919.png)

I guess ```requirements.txt``` is out of sync with ```setup.py```. I don't have errors but IntelliJ thinks I'm missing some dependencies.
![image](https://user-images.githubusercontent.com/32617/142986946-7aca4228-d68d-48a9-83eb-bb85fe4f725c.png)

**Comment by amiorin** [comment]
> @amiorin I think the lock file writes down all the dependencies in the project: https://python-poetry.org/docs/basic-usage/#installing-dependencies

Yes, but it is not used when you do ```pip install openmetadata-ingestion```. You will end up that your users will discover issues before your developers because they use more recent versions of the dependencies. Better not to use things like ```Pipenv``` or ```Poetry``` unless you deploy the Python code doing ```poetry install``` instead of ```pip install```.

**Comment by harshach** [comment]
I think you are only looking at Glue here. I am talking about ingestion to take in credentials with different set of connectors. Each data source have their own version of security implementation, starting with username/password to Kerberos. Hence the reason we need to handle it via env vars. 
So for Glue it makes sense. Let's file a ticket to handle it.
> Credentials are rotated in EC2 instances with Instance Profile. We should stick to the credential provider chain because it doesn't stop our users from providing static credentials but it makes it possible to the more "enterprise" users to use rotation. I know of an example in [Java in Trino](https://github.com/trinodb/trino/blob/d90c1b793213509d34e0a6a345f441db2e7ee9b5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java#L938) but the same thing can be done in boto3 with a custom session.

**Comment by amiorin** [comment]
> I think you are only looking at Glue here. I am talking about ingestion to take in credentials with different set of connectors. Each data source have their own version of security implementation, starting with username/password to Kerberos. Hence the reason we need to handle it via env vars. So for Glue it makes sense. Let's file a ticket to handle it.
> 
> > Credentials are rotated in EC2 instances with Instance Profile. We should stick to the credential provider chain because it doesn't stop our users from providing static credentials but it makes it possible to the more "enterprise" users to use rotation. I know of an example in [Java in Trino](https://github.com/trinodb/trino/blob/d90c1b793213509d34e0a6a345f441db2e7ee9b5/plugin/trino-hive/src/main/java/io/trino/plugin/hive/s3/TrinoS3FileSystem.java#L938) but the same thing can be done in boto3 with a custom session.

Ack

**Comment by harshach** [comment]
> > @amiorin I think the lock file writes down all the dependencies in the project: https://python-poetry.org/docs/basic-usage/#installing-dependencies
> 
> Yes, but it is not used when you do `pip install openmetadata-ingestion`. You will end up that your users will discover issues before your developers because they use more recent versions of the dependencies. Better not to use things like `Pipenv` or `Poetry` unless you deploy the Python code doing `poetry install` instead of `pip install`.

@amiorin 
The project setup with plugin installation option ie. we publish a pypi package per connector such that the users can install what they want instead of installing all using ```pip install openmetadata-ingestion``` we do not document that in any of our docs. A user who needs BigQuery can run ```pip install openmetadata-ingestion[bigquery]``` or redshift ```pip install openmetadata-ingestion[redshift]``` etc.. 
installing using ```pip install openmetadata-ingestion``` is for devs not users. So may be I am missing something how lock file might not help tighten the decencies.

**Comment by amiorin** [comment]
> > > @amiorin I think the lock file writes down all the dependencies in the project: https://python-poetry.org/docs/basic-usage/#installing-dependencies
> > 
> > 
> > Yes, but it is not used when you do `pip install openmetadata-ingestion`. You will end up that your users will discover issues before your developers because they use more recent versions of the dependencies. Better not to use things like `Pipenv` or `Poetry` unless you deploy the Python code doing `poetry install` instead of `pip install`.
> 
> @amiorin The project setup with plugin installation option ie. we publish a pypi package per connector such that the users can install what they want instead of installing all using `pip install openmetadata-ingestion` we do not document that in any of our docs. A user who needs BigQuery can run `pip install openmetadata-ingestion[bigquery]` or redshift `pip install openmetadata-ingestion[redshift]` etc.. installing using `pip install openmetadata-ingestion` is for devs not users. So may be I am missing something how lock file might not help tighten the decencies.

Imagine that both Airflow and Openmetadata adopt somehow a lock file. How can you reconcile shared dependencies with different versions?

**Comment by harshach** [comment]
For Airflow this is an issue for any python workflow which has its own dependencies. This is solved by containerizing the python requirements for the workflows separately so that the scheduler can run the container and execute the workflow inside. This way the dependencies are separated out and doesn't need to worry about different version polluting airflow scheduler/webserver env.

**Comment by harshach** [comment]
To conclude this thread
1. Agree with @amiorin that we should remove requirements.txt etc..
2. Do not use any locking via poetry and use setup.py to manage dependencies
3. Update setup.py such that all requirements are >= version
4. Docker container for airflow is a separate discussion point on how we want to ship the ingestion connectors to the users that are ready to deploy in their docker env.

@amiorin if we are on the same page we can close the discussions and cut few tickets out of this.

**Comment by amiorin** [comment]
👍

**Comment by amiorin** [comment]
I've cut a few tickets out of this. I'm closing.
