### ISSUE TITLE
Ingestion: FiveTran Epic

### ISSUE THREAD

**Issue by ayush-shah** [open-metadata/OpenMetadata#14945]
Lineage:
- [ ] Column level lineage [1.5.0]
- [ ] check for service via elasticsearch in case of case sensitivity from fivetran source side [1.5.0]

Workflow
- [ ] if the pipeline doesn't have any schemas, the workflow breaks, to have a better error handling here [1.5.0]

Task
- [ ] FiveTran Task sourceurl missing [1.5.0]

Status
- [x] Pipeline Status is missing [1.5.0]
- Note there is not Pipeline Status as such, status that we see for connectors are for the testing of connection if they can be reached or not
