### ISSUE TITLE
Ingestion: Performance Improvements to the Ingestion Workflow Epic

### ISSUE THREAD

**Issue by IceS2** [open-metadata/OpenMetadata#15215]
# Overview

Work on different fronts in order to improve the Ingestion Performance.

# TODOs

Logging

- [x] Log Execution Time on DEBUG 

    **PR** - https://github.com/open-metadata/OpenMetadata/pull/15013

Multithreading on the Source side:

- [x] Implement Multithreading for DatabaseServices

    Done at Schema level. It shouldn't affect the performance on the corner cases of having less Schemas than threads but it might affect the performance for the case where we have many Schemas with almost no Tables within.

    **PR** -  https://github.com/open-metadata/OpenMetadata/pull/15130
- [ ] Implement Multithreading for DashboardServices

Incremental Metadata extraction:

- [x] For Snowflake
- [x] For BigQuery

    Done at Table leve using [SNOWFLAKE.ACCOUNT_USAGE.TABLES](https://docs.snowflake.com/en/sql-reference/account-usage/tables). and using Cloud Logging for BigQuery

    **PR** - https://github.com/open-metadata/OpenMetadata/pull/15201
- [x] For Redshift

Batch Process + Sink leaf nodes:

- [ ] For DatabaseServices
- [ ] For DashboardServices

Fire and Forget leaf node requests:

- [ ] Implement a "Fire and Forget" way to send the requests to OpenMetadata for leaf nodes.
    We should collect the results at a later date to create the summary but not block the processing beforehand 🤔
