### ISSUE TITLE
Use native tools to manage backups instead of cli backup/restore

### ISSUE THREAD

**Issue by sushi30** [open-metadata/OpenMetadata#15388]
Following https://github.com/open-metadata/OpenMetadata/issues/15366, we are looking into reducing the development surface by shifting the management of backups to SQL native tools such as `mysqldump` and `pg_dump`. These tools are maintained by the DB teams and communities and are dedicated to solving the problem of creating sql dumps.

In the past there was an issue with mysqldump and `GENERATED` columns:
- Stackoverflow: [mysqldump goes nuts when first column is generated](https://stackoverflow.com/questions/72058990/mysqldump-goes-nuts-when-first-column-is-generated)
- MySQL Bug #81926: https://bugs.mysql.com/bug.php?id=81926

These issues are resolved in mysqldump 8.3.

## Proposed Solutions

1. Add a deprecated message on the CLI tools `metadata backup` and `metadata restore`.
2. Since, the OM docker deployment uses mysql 8.0 and mysqldump is backward compatible, add the mysqldump 8.3 binary to the ingestion container.
3. Add documentation with examples for how to use the SQL native tools.

## Subtasks

- [x] test on sandbox
- [ ] Add docs about "minimal" backup (maybe skip the events or sessions table)
- [x] https://github.com/open-metadata/OpenMetadata/pull/15506
