### ISSUE TITLE
Implement encryption at rest

### ISSUE THREAD

**Issue by amiorin** [open-metadata/OpenMetadata#2486]
# Intro
We will add encryption at rest in OM and in Airflow. The first PR #2488 is for OM. A second PR will follow for Airflow.

# Tasks
## First PR
- [x] Implement prepare method of DatabaseServiceRepository.
- [x] Implement rotation.
- [x] Implement [rotator] using the CLI (https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html#rotating-encryption-keys) like Airflow.
- [x] Add the prefix `fernet:`
- [x] Decrypt DatabaseConnection if encrypted for admin, bots, and owner
- [x] Decrypt deploy to airflow if admin or bots.
- [x] Add env variable for the FernetKey
- [x] Write the manual for OpenMetadata
- [x] Test with helm charts
- [ ] Migrate webhooks to use the fernet key.

## Second PR
- [ ] TBD
- [ ] Write the manual for Python.

# Requirements
1. Single source of truth
1. Encryption at rest
1. No breaking changes

# Assumptions
1. OpenMetadata has TLS.

# Ignore everything below this, only for reference

# UI steps
1. Create a new service
2. Create a new ingestion

# CLI steps
The service is defined, the database connection is defined, the user has the privilege to get the database connection password in clear text, and the user is using the new configuration schema
1. Create a new DAG in Airflow
2. Run it locally
3. Deploy

The user is using the old configuration schema
1. Ignore the old fields in the configuration schema
2. Print a warning that the configuration schema has changed
3. Pull the service with the database connection from the OM

The user doesn't have the privileges to get the database connection in clear
1. Exit with error and print the instruction to obtain the privilege.

The service is not defined
1. Exit with error and print the instruction to define the service in the UI.

The service is defined but the database connection is not defined
1. Exit with error and print the instruction to define the database connection for the service in the UI.

# Glue
Glue will use his own schema and UI wizard.

# Implementation details
1. We version the tokenized database connection to be able to undo deletion without breaking the ingestion process.
2. The ingestion framework in Python uses non-deleted services. If the service is deleted we are in the not found case.

Current schema.
```json
{
  "source": {
    "type": "mysql",
    "config": {
      "username": "openmetadata_user",
      "password": "openmetadata_password",
      "database": "openmetadata_db",
      "service_name": "local_mysql",
      "schema_filter_pattern": {
        "includes": [
          "test_delete.*"
        ]
      }
    }
  }
}
```

New schema, all previous fields are optional and generate a warning.

```json
{
  "source": {
    "type": "mysql",
    "config": {
      "service_name": "local_mysql",
      "schema_filter_pattern": {
        "includes": [
          "test_delete.*"
        ]
      }
    }
  }
}
```

The initial idea was to remove the DatabaseConnection object if not admin or bot but then I have realized that we have the version API that will store previous versions of DatabaseConnection making the removal of DatabaseConnection non-trivial.

I decided then on another approach similar to how Airflow manages DatabaseConnections. I've found a fernet library in Java that should be compatible with Python.

The Python code deployed in Airflow by OM will retrieve the DatabaseConnection every run. We are sure about connectivity between the Python code and OM because the Python needs to push the metadata extracted from the underlying system.

- [x] Implement prepare method of DatabaseServiceRepository.
- [x] Implement rotation.
- [x] Implement [rotator](https://airflow.apache.org/docs/apache-airflow/stable/security/secrets/fernet.html#rotating-encryption-keys) like Airflow.
- [x] Add REST API to decrypt/encrypt strings
- [x] Add the prefix `fernet:`
- [ ] Change the python code to decrypt the DatabaseConnection every run.
- [ ] Add cli to encrypt/decrypt Workflow config files
- [ ] Add env variable for the FernetKey
- [ ] Add rotate to `EntityRepository`
- [ ] Write the manual for Java.
- [ ] Write the manual for Python.
- [ ] Migrate webhooks to use the fernet key.

# Q&A
Q) How does clients like bots can retrieve these passwords in decrypted strings
A) Bots with specific roles will get the decrypted password with the normal `databaseService` collection.

Q) Can't we just disable the recordChange to capture the sensitive information like passwords?
A) I don't think it's needed. The encrypted password can be store in the versioning.

Q) Encryption is always better but it shouldn't introduce complexity on the client side. Example as a bot or admin who has access should be able to get these passwords in plaintext. We can SSL connection to make sure they are encrypted wire
A) The new design includes this feedback.

**Comment by harshach** [comment]
@amiorin can you add more details here
1. How does clients like bots can retrieve these passwords in decrypted strings
2. Can't we just disable the recordChange to capture the sensitive information like passwords?
3. Encryption is always better but it shouldn't introduce complexity on the client side. Example as a bot or admin who has access should be able to get these passwords in plaintext. We can SSL connection to make sure they are encrypted wire

**Comment by amiorin** [comment]
I'm on it.
