### ISSUE TITLE
Service Connection & Schema Name - Tracker

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#3820]
List down all issues related to the refactor of the Service Connection as a JSON Schema from https://github.com/open-metadata/OpenMetadata/pull/3804

- https://github.com/open-metadata/OpenMetadata/issues/3819
- https://github.com/open-metadata/OpenMetadata/issues/3821
- https://github.com/open-metadata/OpenMetadata/issues/3843
- https://github.com/open-metadata/OpenMetadata/issues/3844
- https://github.com/open-metadata/OpenMetadata/issues/3849
- https://github.com/open-metadata/OpenMetadata/issues/3850
- https://github.com/open-metadata/OpenMetadata/issues/3857
- https://github.com/open-metadata/OpenMetadata/issues/3863
- https://github.com/open-metadata/OpenMetadata/issues/3864
- https://github.com/open-metadata/OpenMetadata/issues/3865
- https://github.com/open-metadata/OpenMetadata/issues/3866
- https://github.com/open-metadata/OpenMetadata/issues/3867
- https://github.com/open-metadata/OpenMetadata/issues/3868
- https://github.com/open-metadata/OpenMetadata/issues/3869
- https://github.com/open-metadata/OpenMetadata/issues/3876
- https://github.com/open-metadata/OpenMetadata/issues/3879
- https://github.com/open-metadata/OpenMetadata/issues/3886
- https://github.com/open-metadata/OpenMetadata/issues/3593
- https://github.com/open-metadata/OpenMetadata/issues/3918
- https://github.com/open-metadata/OpenMetadata/issues/3931
- https://github.com/open-metadata/OpenMetadata/issues/3932
- https://github.com/open-metadata/OpenMetadata/issues/3944
- https://github.com/open-metadata/OpenMetadata/issues/3948 - P2
- https://github.com/open-metadata/OpenMetadata/issues/3955 - bug
- https://github.com/open-metadata/OpenMetadata/issues/3962 - bug
- https://github.com/open-metadata/OpenMetadata/issues/4000
- https://github.com/open-metadata/OpenMetadata/issues/4012
- https://github.com/open-metadata/OpenMetadata/issues/4028
- https://github.com/open-metadata/OpenMetadata/issues/4076
- https://github.com/open-metadata/OpenMetadata/issues/4096
- https://github.com/open-metadata/OpenMetadata/issues/4131
---
## Airflow REST & Ingestion Pipeline

- https://github.com/open-metadata/OpenMetadata/issues/4129
- https://github.com/open-metadata/OpenMetadata/issues/4089

## Connectors

- [x]  amundsen @harshach 
- [x] athena -> check https://github.com/open-metadata/OpenMetadata/issues/3918
- [ ]  atlas
- [x] azuresql
- [x]  bigquery -> check https://github.com/open-metadata/OpenMetadata/issues/3965
- [x]  bigquery-usage
- [x]  clickhouse
- [x]  clickhouse-usage
- [x]  databricks
- [x]  db2
- [x]  deltalake
- [x] druid @harshach 
- [x] dynamodb
- [x]  glue
- [x] hive
- [x] kafka @harshach 
- [ ] ldap_users
- [x] looker
- [x] mariadb
- [x] metabase
- [x] metadata (elasticsearch)
- [ ] mlflow @pmbrull -> 0.11
- [x] mssql
- [x] mssql-usage
- [x] mysql
- [ ] neo4j-helper (dbt?) @harshach 
- [x] oracle
- [x] postgres
- [x] powerbi
- [x] presto
- [x] redash
- [x] redshift
- [x] redshift-usage
- [x] salesforce
- [x] sample_data
- [x] sample_usage
- [x] singlestore
- [x] snowflake
- [x] snowflake-usage
- [x] sqlite
- [x] superset
- [x] tableau
- [x] trino
- [x] vertica

---
## Tests
- https://github.com/open-metadata/OpenMetadata/issues/3823
- https://github.com/open-metadata/OpenMetadata/issues/3824
- https://github.com/open-metadata/OpenMetadata/issues/3825
- https://github.com/open-metadata/OpenMetadata/issues/3826
- https://github.com/open-metadata/OpenMetadata/issues/3827
- https://github.com/open-metadata/OpenMetadata/issues/3828
- https://github.com/open-metadata/OpenMetadata/issues/3829
- https://github.com/open-metadata/OpenMetadata/issues/3830

**Comment by pmbrull** [comment]
@open-metadata/ui hi @darth-coder00

**Comment by pmbrull** [comment]
Thanks for the work. Closing this
