### ISSUE TITLE
UI: Explore page filters should include service name

### ISSUE THREAD

**Issue by vivekratnavel** [open-metadata/OpenMetadata#3928]
Closes #3698 
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
UI

**Tasks**
<img width="265" alt="Screen Shot 2022-04-07 at 10 04 40 PM" src="https://user-images.githubusercontent.com/1051198/162368505-e287441d-79b9-45af-8ae1-8d35e4120ea8.png">

- [x] The services and databases displayed in the filters section should be sorted by the count
- [x] Add an option to filter by service name and Schema
- [x] #3993
- [x] Each table card listed in the main section should have the service name and schema displayed
- [x] Topics, Dashboards, and Pipelines should have options to filter by service name and Tags
