### ISSUE TITLE
UI : Support adding custom fields to an entity

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [open-metadata/OpenMetadata#5054]
Refer #4920 

**Related issues**

- [ ] [Mocks : Provide a mock up for Support adding custom fields to an entity #5055](https://github.com/open-metadata/OpenMetadata/issues/5055)

- [ ] [UI : Add support for creating metadata types #5056](https://github.com/open-metadata/OpenMetadata/issues/5056) 

- [ ] [UI : Add support for adding a field to an entity type. #5057](https://github.com/open-metadata/OpenMetadata/issues/5057)

**Comment by Sachin-chaurasiya** [comment]
Closing this issue, as we will be only working on the issue #5057
