### ISSUE TITLE
Custom SQL Data Quality Tests

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#5998]
## Context
#5973  introduces the possibility for user to enter custom SQL as a way to create custom tests. Currently this SQL statement is input in a simple `label` field -- see image below. The current implementation limits the user experience. To provided an improved user experience we would like to introduce support for a full SQL editor.

The editor should have at minimum the following features:
- good SQL support (e.g. syntax highlithing, tab indentation, line number, etc.)
- SQL syntax validation (i.e. the ability for a user to validate their query)

![](https://user-images.githubusercontent.com/13626425/178032382-dd06e360-a5aa-489e-811e-1e4b7d48817b.png)

## Backend
- We'll need to have an endpoint to execute the query input from the user against the specified service
    - validation -> rights, limit to select only, etc.
         - How to run the validation (simple request or part of a workflow?)
    - query timeout logic
    - Sample data  return for the user to validate the test return what is expected (i.e. no rows on tests passing rows and tests failing)

## Ingestion
- [x] https://github.com/open-metadata/OpenMetadata/pull/5973
- [x] https://github.com/open-metadata/OpenMetadata/issues/6050
- [x] #10036
- [ ] #9686

## Frontend
- [ ] https://github.com/open-metadata/OpenMetadata/issues/5998
- [ ] support for SQL editor features (autocompletion, etc.)
- [ ] showcase sample data for user to validate the tests run as expected

**Comment by harshach** [comment]
@TeddyCr we can close this out right?

**Comment by TeddyCr** [comment]
@harshach this an epic. I think we still have some elements to tackle here:
1. Test SQL Statement (validate syntax is good + return sample data)
2. Add custom validation logic (right now the test to pass needs to either return 0 row or the value 0 but user may want to have more customized logic)
