### ISSUE TITLE
UI | Improve Search/Explore page - allow complex searching and offer more suggestions

### ISSUE THREAD

**Issue by mosiac1** [open-metadata/OpenMetadata#6189]
**Is your feature request related to a problem? Please describe.**
Users are reporting the search page is not good enough. The issues they run into are either: 
 - a slight difference in names cause a resource not to be displayed at all
 -  searching for a service/database/schema does not yield any relevant results (neither a link to the service/database/schema or tables/topic/etc. under it)
 - getting to a search only in a particular database/schema is still convoluted. Either navigate to it, start typing in search and click "Search in this database/schema" or try setting it the complex search.

**Describe the solution you'd like**
Some points I would like to tackle:
- [ ] The "Complex Search" section should always be below the search in `/explore`. Users have a hard time spotting the dropdown and using it.
- [ ] Users should be able to add multiple filters on the same resource (database/schema/service etc.). Filters for the same resource should be ORd together and ANDed with all other filters.
- [ ] Users should be able to freely enter any text in the complex search, not be limited to options.
- [ ] Users should receive suggestions for the complex search fields. These suggestions should be aware of the context - the value of other filters - so they offer relevant suggestions.
- [ ] Text search should also by default search in a table's database, schema, and service.
- [ ] Text search for tables should display as possible results Services, Databases, and Schemas along with the tables (in the main column). They should be clickable to go to the page of the resource or add that resource as a filter.

Another way of handling some of the issues here would be to add search bars on the left-hand side panel of `/explore` so users can search through resources.

**Additional context**

I would really appreciate feedback on these suggestions, maybe a design session to find the best way to tackle these issues.

**Comment by mosiac1** [comment]
Inspiration:

Jira's search is based on a relatively simple search syntax and offers a simple search (UI-based, easy to use, intuitive, lots of suggestions, etc.) and an advanced search that is a text box, allowing any queries.

Creating a fully custom search syntax would be a very big feature - we should investigate initial implementations.

**Comment by mosiac1** [comment]
Regarding the point 
> - [ ] Users should be able to add multiple filters on the same resource (database/schema/service etc.). Filters for the same resource should be ORd together and ANDed with all other filters.

Forcing users into this AND and OR behavior is not a good idea. It makes sense for some use cases and not for others. This is mainly what sparked the Jira query language discussion - allowing users the flexibility to mix and match filters.

**Comment by mosiac1** [comment]
Yeah I will look into creating a POC this week

**Comment by mosiac1** [comment]
Update:

The design I've been working on is based on using https://www.npmjs.com/package/react-awesome-query-builder.

My idea is to add a UI-based complex query builder (see screenshots) which allows users to combine filters with logical operators to get to the data they are looking for.

The feature is quite big so I will be splitting it up into a number of PRs. For now, the structure should follow:

1.  Extend the search API to support Elasticsearch filters as parameters and move off using EQL to filter results. 
2. Add initial query builder
3. Update the advanced search field to work in tandem with the new feature

**Comment by mosiac1** [comment]
![query builder](https://user-images.githubusercontent.com/88427079/186899786-a1bd9d61-1e2a-4718-9acc-5054feac4443.png)

**Comment by mosiac1** [comment]
Update: we discussed on zoom and decided to split this feature up into 2 primary PRs:
1. Adding the improved search API and logical query builder, changes to explore page and facet filters
2. Refactoring existing search API calls to use the new interface and types

So https://github.com/open-metadata/OpenMetadata/pull/6965 will be closed and a new PR will be open

**Comment by mosiac1** [comment]
PR https://github.com/open-metadata/OpenMetadata/pull/8083 has been merged!

**Comment by mosiac1** [comment]
Open https://github.com/open-metadata/OpenMetadata/pull/8140 which has the main code fort the Logical Query Builder

**Comment by mosiac1** [comment]
Initial implementation of the query builder is merged, closing
