### ISSUE TITLE
Feature request for Glossary- Moove.io

### ISSUE THREAD

**Issue by lailapatel** [open-metadata/OpenMetadata#6661]
- [x] Feature for adding assets against the glossary term (directly from the glossary option).
- [ ] Owners to be tagged against the glossary term (directly from the glossary option).
- [ ] Association among tags (e.g. if Tag A and Tag B are interlinked, then upon applying Tag A to a term, Tag B should also be applied automatically).
- [ ] ~~Tag on a parent term should get populated on the child term, but it should be flexible for cases where the user wants to remove it.~~
@lailapatel, we will not be doing this as this may not be applicable in many scenarios.

**Comment by lailapatel** [comment]
kindly consider the addition of below feature also, as it is related to point 4:

5. Owners and Reviewers for Parent term (in glossary) should be populated on child term, with a flexibility for the users to change it (if required in case).

**Comment by harshach** [comment]
@vivekratnavel @devyani-kaushik this glossary and list of features here https://github.com/open-metadata/OpenMetadata/issues/7074
lets handle all of these issues and come up with improved UX for the next couple of weeks

**Comment by chirag-madlani** [comment]
Tracking Glossary improvements here: #7074

**Comment by lailapatel** [comment]
Kindly consider below feature along with the above Glossary level backend features:

**Comment by sureshms** [comment]
> 
> Correspondence over the business terms to be enabled under the glossary option.

@lailapatel can you please add more details here? Who is corresponding, over what, and what details are the corresponding about?

**Comment by lailapatel** [comment]
@sureshms surely.

Have consolidated the requirements which were discussed above. Elaboration to bulk upload of glossary is in 1.2.

1. Glossary:

1.1 Feature for adding assets against the glossary term (directly from the glossary option).
 - Currently, physical assets can only be tagged to a glossary term if user goes to required physical tables and add tags.

1.2 Correspondence over the business terms to be enabled under the glossary option.
  - Currently, correspondence/ communication option is available at table -column level, where users (stewards, owners, reviewers/other users) can mark/mention stakeholders and correspond for physical assets/terms.
- Correspondence / communication if available under Glossary option, then reviewers and owners of the terms can communicate and discuss their thoughts using the same option.
  
1.3 Bulk upload of glossary through gsheet/excel/csv.
- This will help in uploading the current version of manual glossaries.

2. Tags

2.1  Owners and Reviewers for Parent term (in glossary) should be populated on child term, with a flexibility for the users to change it (if required in case).

2.2 Association among tags (e.g. if Tag A and Tag B are interlinked, then upon applying Tag A to a term, Tag B should also be applied automatically).

2.3 In continuation to above, the Tag on a parent term should get populated on the child term, but it should be allow the users to remove /change it (depending on case to case basis).

**Comment by chirag-madlani** [comment]
@harshach Please check this, and let us know if anything pending from the list

**Comment by harshach** [comment]
@chirag-madlani lets work on the following for 1.0

- [ ] Feature for adding assets against the glossary term (directly from the glossary option).  Let's use search option to allow users to select an entity and use patch to apply the glossary term on the entity. 
- [ ] Owners and Reviewers for Parent term (in glossary) should be populated on child term, with a flexibility for the users to change it (if required in case). cc @mohityadav766

**Comment by sureshms** [comment]
@lailapatel, I am marking this as done. Can you open separate issues for any items that are not done? It would be good to have a separate issue for each request instead of one big issue. Thank you.

**Comment by lailapatel** [comment]
Hello @sureshms
