### ISSUE TITLE
Glossary Improvements

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7074]
**Is your feature request related to a problem? Please describe.**
for 0.12.1 we need to improve several aspects of Glossary. Below captures the few details of what we want to achieve in Glossary for 0.12.1

**Describe the solution you'd like**

- [ ] Allow users add to tags during the creation process
- [ ] Styling of adding Related Terms and Synonyms is different. We should provide the similar experience
- [ ] Remove deleted Glossary terms out of the search suggestions
- [ ] Improve Assets listing of Glossary Term
- [ ] Allow users to rename the Glossary Term
- [ ] Allow users to move children of glossary to another glossary in a nested fashion
- [ ] Adding Tags at the root of Glossary should be applied to everyone underneath that
- [ ] Adding Reviewers at the root of Glossary should be applied to all the children of Glossary
- [ ] Bulk upload of Glossary Terms
- [ ] Allow users to add entities to a GlossaryTerm from Glossary Asset page
- [ ] Applying Tag Category should apply all the related tags

**Describe alternatives you've considered**

**Additional context**

**Related issues**
- ...

**Comment by harshach** [comment]
- [ ] https://github.com/open-metadata/OpenMetadata/issues/7077

**Comment by trillhaa** [comment]
Two more suggestions (second is a bit of a long-shot):
1. Set Asset as "Primary Asset" for a given glossary term: There might be many tables associated to one Glossary term, but one table is the base/key table. I should be able to mark one table /asset as "primary" for that glossary term.
2. Auto-assign glossary terms to columns/assets based on exact string matches. This would be a huge improvement.

**Comment by harshach** [comment]
@ShaileshParmar11 @devyani-kaushik lets pick few of these todos for 0.12.1

**Comment by vivekratnavel** [comment]
- [ ] Trailing space in display name and FQN of glossary term is not handled correctly

https://user-images.githubusercontent.com/1051198/189989414-667852ca-469e-49a7-a4a5-99a51cd5b333.mov

Response:
```
{"data":[{"id":"4ab215ee-7854-4455-9078-7ea0ee819fed","name":"Test ","displayName":"Test ","description":"Testing here","fullyQualifiedName":"Test Service.Test ","synonyms":["Random"],"glossary":{"id":"8f94f9a9-2756-4b7f-99a8-459117c0e462","type":"glossary","name":"Test Service","fullyQualifiedName":"Test Service","description":"test","displayName":"Test Service","deleted":false,"href":"http://sandbox-beta.open-metadata.org/api/v1/glossaries/8f94f9a9-2756-4b7f-99a8-459117c0e462"},"children":[],"relatedTerms":[{"id":"4ab215ee-7854-4455-9078-7ea0ee819fed","type":"glossaryTerm","name":"Test ","fullyQualifiedName":"Test Service.Test ","description":"Testing here","displayName":"Test ","deleted":false,"href":"http://sandbox-beta.open-metadata.org/api/v1/glossaryTerms/4ab215ee-7854-4455-9078-7ea0ee819fed"},{"id":"4ab215ee-7854-4455-9078-7ea0ee819fed","type":"glossaryTerm","name":"Test ","fullyQualifiedName":"Test Service.Test ","description":"Testing here","displayName":"Test ","deleted":false,"href":"http://sandbox-beta.open-metadata.org/api/v1/glossaryTerms/4ab215ee-7854-4455-9078-7ea0ee819fed"}],"references":[{"name":"Test Service","endpoint":"https://github.com/open-metadata/OpenMetadata/issues/7248"}],"version":0.7,"updatedAt":1663095766554,"updatedBy":"vivek","href":"http://sandbox-beta.open-metadata.org/api/v1/glossaryTerms/4ab215ee-7854-4455-9078-7ea0ee819fed","reviewers":[],"tags":[{"tagFQN":"PersonalData.Personal","description":"Data that can be used to directly or indirectly identify a person.","source":"Tag","labelType":"Manual","state":"Confirmed"},{"tagFQN":"PersonalData.SpecialCategory","description":"GDPR special category data is personal information of data subjects that is especially sensitive, the exposure of which could significantly impact the rights and freedoms of data subjects and potentially be used against them for unlawful discrimination.","source":"Tag","labelType":"Manual","state":"Confirmed"},{"tagFQN":"PII.None","description":"Non PII","source":"Tag","labelType":"Manual","state":"Confirmed"},{"tagFQN":"PII.NonSensitive","description":"PII which is easily accessible from public sources and can include zip code, race, gender, and date of birth.","source":"Tag","labelType":"Manual","state":"Confirmed"}],"changeDescription":{"fieldsAdded":[],"fieldsUpdated":[],"fieldsDeleted":[{"name":"tags","oldValue":"[{\"tagFQN\":\"PII.Sensitive\",\"description\":\"PII which if lost, compromised, or disclosed without authorization, could result in substantial harm, embarrassment, inconvenience, or unfairness to an individual.\",\"source\":\"Tag\",\"labelType\":\"Manual\",\"state\":\"Confirmed\"}]"}],"previousVersion":0.6},"status":"Draft","deleted":false}],"paging":{"total":1}}
```

**Comment by sureshms** [comment]
- [ ] Instead of showing the entire fqn for tags and glossaries, we should show only the leaf node name based on the display name of that node. When hovering over, we can show the FQN. Currently, tags and glossary terms seem too busy when used as tag labels.
- [ ] Suggest/Add a glossary term followed by review and accept workflow should be streamlined.
- [ ] We need to add more tags and glossaries out of the box. Few examples - domains, data life cycle tags, etc.

**Comment by vivekratnavel** [comment]
- [ ] Fix Glossary menu inconsistency while navigating between Related Terms
https://user-images.githubusercontent.com/1051198/190272738-485c481a-193c-409c-bfe9-3e223b3830d2.mov

**Comment by vivekratnavel** [comment]
- [ ] #7471 
- [ ] #7472

**Comment by devyani-kaushik** [comment]
https://www.figma.com/file/VaeQD2fIhQVDCvqBHyEv7J/Open-Metadata?node-id=14323%3A22945

**Comment by ShaileshParmar11** [comment]
> * [ ]  Fix Glossary menu inconsistency while navigating between Related Terms
> 
>  190272738-485c481a-193c-409c-bfe9-3e223b3830d2.mov

Hello, @vivekratnavel I am not able to reproduce the mentioned issue!
are there any specific steps that need to be followed?


https://user-images.githubusercontent.com/71748675/192106858-87d65144-f21f-4a63-97d0-71fee3541d76.mov

**Comment by vivekratnavel** [comment]
Hi @ShaileshParmar11, I don't have any specific steps. If you are not able to reproduce it, then we can mark it resolved. Thank you!

**Comment by vivekratnavel** [comment]
@ShaileshParmar11, I was able to reproduce the issue. Can you please check?
 

https://user-images.githubusercontent.com/1051198/192869925-16b8c955-1308-4359-a6a0-186ef9edbdcd.mov

**Comment by TeddyCr** [comment]
@harshach can I take "Bulk upload of Glossary Terms - P1 - 0.13.0"?
