### ISSUE TITLE
0.12.1 Release Checklist 

### ISSUE THREAD

**Issue by harshach** [open-metadata/OpenMetadata#7612]
Below are the tests that we need to automate or run manually to mark 0.12.1 release
- [ ] automated upgrade tests from 0.12.0 to 0.12.1. - @akash-jain-10 
- [ ] automated upgrade tests from 0.11.5 to 0.12.1 - @akash-jain-10 
- [ ] tests should run previously deployed workflows and check if the workflow succeeds (including testSuite workflow) - @TeddyCr 
- [x] bring up instance with JWT token enabled secured OpenMetadata server in 0.11.5 or 0.12.0 , installing new 0.12.1 should transform them into user/password login. This would require users to migrate to new configs. But everything else continue to work.  - @mohityadav766 @chirag-madlani 
- [x] In previous setup, non-secure mode will not have ingestion bot setup. When they migrate ingestion bot should setup with JWT token - @mohityadav766 @chirag-madlani 
- [ ] Update docs to point to the new configs - @harshach @akash-jain-10 @pmbrull 
- [x] Update all ingestion docs not just the UI but Airflow SDK and running using metadata to check all the configs are correct
Please add any other cases I missed here based on our support activity - @ulixius9 
- [ ] When upgrading to 0.12.1, `TestDefinition`  with `entityType=COLUMN` should have a `supportedDataType` field that is not null 
- [x] https://github.com/open-metadata/OpenMetadata/issues/7769
- [x] https://github.com/open-metadata/OpenMetadata/issues/7709
- [x] Airflow 2.3.4

**Comment by pmbrull** [comment]
Airflow 2.3.4 not needed for 0.12.1. The migration issue is internal in Airflow and we'll provide the docs on how to update it properly based on Airflow's known issues

**Comment by harshach** [comment]
- [x] Manual test - Baremetal upgrade tests from non-secure to basic auth (0.11.5 - 0.12.1)
- [x] Manual test - Baremetal upgrade tests from secure(google sso) to secure (0.11.5 - 0.12.1)
- [x] Manual test - baremetal upgrade tests from secure with jet to secure with jet token(0.11.5 - 0.12.1)

**Comment by harshach** [comment]
- [ ] docker upgrade tests with secure (google sso)  -> secure (google sso) -> 0.11.5 - 0.12.1 @ShaileshParmar11 
- [ ] docker upgrade tests with secure (okta sso) -> secure (okta sso) -> 0.11.5 - 0.12.1 @Sachin-chaurasiya 
- [ ] What's new - 0.12.1 - @chirag-madlani @harshach

**Comment by harshach** [comment]
Test Procedure
1. Bring up 0.11.5 with connectors (snowflake, redshift etc..) and tests, sample data
2. Generate user activity by assigning ownership, updating descriptions, tags, glossary
3. Upgrade to 0.12.1 with docker
4. check if ingestion connectors and tests can be deployed and every features works ok

**Comment by harshach** [comment]
docker testing https://docs.google.com/document/d/1RkYhn9Z4WfUZUMEX9ynqYlzEIk_1MZWyVOvB3RwvgiE/edit#heading=h.o0ytzg7clk7c

**Comment by ayush-shah** [comment]
Add docs related to SSL -> @ayush-shah 
#7578 #7577

**Comment by mohityadav766** [comment]
bring up instance with JWT token enabled secured OpenMetadata server in 0.11.5 or 0.12.0 , installing new 0.12.1 should transform them into user/password login. This would require users to migrate to new configs. But everything else continue to work. - tested works fine
