### ISSUE TITLE
Add data health indicator

### ISSUE THREAD

**Issue by TeddyCr** [open-metadata/OpenMetadata#8118]
Data health should be an indicator showing the health of the platform as a whole. It would be for business users primarely and should summarize the state of the platform.

- [ ] determine what should consist a health (should probably allow user to pick dimensions/metrics that we'll then use to compute)
- [ ] Decide where data health should be displayed and how -> mock design
- [ ] Implement computation logic

**Comment by TeddyCr** [comment]
Will part of the DI re work and data quality reports
