### ISSUE TITLE
DBT Features List

### ISSUE THREAD

**Issue by OnkarVO7** [open-metadata/OpenMetadata#8486]
**Implemented features for DBT:**
- Showing DBT queries on UI
- DBT node/table lineage
- DBT column level lineage (only possible if query is parsable by lineage parser)
- DBT Tests and test results
- Adding owner/team from DBT into OpenMetadata
- Ingesting table and column level tags from DBT into OpenMetadata
- DBT descriptions (toggle is added if descriptions should be overridden from DBT)
- [DBT Tag Category name](https://github.com/open-metadata/OpenMetadata/issues/7972)
- [Handle multiple DBT projects for a single service](https://github.com/open-metadata/OpenMetadata/issues/5559)

**To be considered Feature List:**
- [Exposures](https://docs.getdbt.com/docs/build/exposures) (example in [metabase](https://github.com/gouline/dbt-metabase)) - Exposures make it possible to define and describe a downstream use of your dbt project, such as in a dashboard, application, or data science pipeline
- [DBT Lineage when there are intermediate not-materialized models](https://github.com/open-metadata/OpenMetadata/issues/6874)
- [Add support for test_suite_name meta defined in model schemal.yaml file](https://github.com/open-metadata/OpenMetadata/issues/7743)
-  Parse dbt queries for fetching frequently joined table data

**Issues/Bug List:**
- [x] [DBT errors if tests are present in manifest but run_results file is not passed](https://github.com/open-metadata/OpenMetadata/issues/8455)
- [x] [DBT - Issue while adding descriptions](https://github.com/open-metadata/OpenMetadata/issues/8535)
- [ ] 1.2 - Clean dbt tags that are not appearing in the models anymore (from [comment](https://github.com/open-metadata/OpenMetadata/issues/8486#issuecomment-1548782916))
- [x] https://github.com/open-metadata/OpenMetadata/issues/9011
- [ ] 1.2 - https://github.com/open-metadata/OpenMetadata/issues/9031
- [x] https://github.com/open-metadata/OpenMetadata/issues/10184
- [x] https://github.com/open-metadata/OpenMetadata/issues/6874

**Comment by geoHeil** [comment]
https://github.com/open-metadata/OpenMetadata/issues/9011

**Comment by geoHeil** [comment]
- column level lineage for DBT projects with macros https://github.com/open-metadata/OpenMetadata/issues/9011
- tier sync https://github.com/open-metadata/OpenMetadata/issues/9031
- arbitrary key/value sync as extra properties https://github.com/open-metadata/OpenMetadata/issues/9637

**Comment by OnkarVO7** [comment]
- https://github.com/open-metadata/OpenMetadata/issues/10199
- https://github.com/open-metadata/OpenMetadata/issues/10184
- https://github.com/open-metadata/OpenMetadata/issues/8561

**Comment by harshach** [comment]
@OnkarVO7 can you update the ticket with what are we solved so far and what is remaining. Looking at the issue I am not able to tell if shipped some of these already

**Comment by OnkarVO7** [comment]
@harshach the list mentioned under Implemented section [here](https://github.com/open-metadata/OpenMetadata/issues/8486#issue-1431967892) are resolved. Rest others are remaining

**Comment by OnkarVO7** [comment]
Show dbt fields in the UI https://github.com/open-metadata/OpenMetadata/issues/10502

**Comment by yu-iskw** [comment]
Synchronizing back to metadata to dbt would be crucial as we import metadata from dbt, I suppose.
https://www.castordoc.com/blog/now-live-sync-back-to-dbt

https://openmetadata.slack.com/archives/C02DZK3QH8Q/p1678973195319499

**Comment by heroWang** [comment]
Background: 
	English is not my native language. So, my level of English may lead to communication barriers. If there are any unclear expressions, please let me know.
	We are only at the documentation stage with OMD, so we cannot provide recommendations from a design perspective, but I can give you my requirements:

1. Metric sharing. 
	Basic metric search functionality, similar to that of a data table, where metrics can be tagged and associated with a glossary. Additionally, descriptions of the metric's dimensions, statistical granularity, business limitations, and derived relationships between metrics should be provided to allow users to perceive subtle differences between different metrics.
2. Metric query agent. 
	Based on managing the physical tables on which the metrics depend, as well as their dimensions and granularity, the agent can generate query SQL based on user parameters and submit the SQL to the data warehouse to obtain data samples.

3. It would be best to implement the aforementioned requirements using dbt as the data source.

Reference materials: 
https://docs.transform.co/docs/metricflow/metricflow-tutorial
https://docs.getdbt.com/docs/build/metrics

**Comment by quguangyu0321** [comment]
Hi, guys.  i updated new tag in dbt and ingest it into openmetadata again.
but i found that old tag still remained. is it possible to add this feature in enhancement(remove the old metadata automatically)?

**Comment by OnkarVO7** [comment]
Closing the issue and opening separate issues for the remaining features
https://github.com/open-metadata/OpenMetadata/issues/12909
https://github.com/open-metadata/OpenMetadata/issues/12910
https://github.com/open-metadata/OpenMetadata/issues/12911
