### ISSUE TITLE
UI: Lineage improvements

### ISSUE THREAD

**Issue by ShaileshParmar11** [open-metadata/OpenMetadata#8521]
- [x] UI improvement as per new mocks - #8568
- [x] Pipeline as edge
- [x] function as edge for column lineage (show function icon if function information is present for column lineage) - #8568
- [x] Lineage tracing (onClick of node highlight full path of upstream as well as downstream) #8542
- [x] onClick of Edge shows its details inside the drawer & Show Function details for column edges #8599
- [ ] #8704
- [x] connect edge on the drop of anywhere on the node #8631
- [x] Search box option for lineage #8609

**Comment by stevenspadotto** [comment]
A feature to filter the Lineage graph by tags assigned to assets would be helpful, especially when the Lineage graph displays hundreds or thousands of nodes.

**Comment by ShaileshParmar11** [comment]
For pending tasks created a separate issue
#8705 #8704
