### ISSUE TITLE
Refactor of the secrets manager

### ISSUE THREAD

**Issue by nahuelverdugo** [open-metadata/OpenMetadata#8577]
**Issue**
Current secrets manager implementations have the following drawbacks by saving the JSON objects as a secret:
- It adds a lot of complexity to our code, e.g., migrations, dealing with retro compatibility, extra serialization/deserialization of objects, etc.
- Scalability and compatibility among different available secrets manager implementations. The amount of data you can save on each one differs and is limited. We are storing JSON objects as string values that do not have fixed lengths.
- The user loses the advantage of using a secret manager store/vault since we store the JSON object.

**New approach**
What we want to achieve is to be able to recover those passwords/secrets during the workflow execution. We can achieve the same by using a `CustomSecretStr` in our `pydantic` models and using values like `secret:my-secret-id` for the passwords. So each time we want a value for a password, we call `get_secret_value()`, and our `CustomSecretStr` will check if the value starts with `secret:` and recover it from the configured secrets vault. 

The advantages of the new approach are:

- Reduce the complexity of the backend, and we can remove the SecretsManager dependency from many places and the CLI code.
- It is easy to implement and valuable for the user.
- It still makes our application secure since no sensitive values are stored.

**Tasks**
- [x] Replace the current managed secret manager implementation with a non-managed version. This will include adding `CustomSecretStr` when the code is generated and migrating the connection parameters and options into a list of values and passwords so the same approach can be applied to these objects. 
  - https://github.com/open-metadata/OpenMetadata/pull/8617
- [x] Review connection JSON schemas to see if there is any sensitive value that is not being treated as a password.
  - Moved into a separate issue: https://github.com/open-metadata/OpenMetadata/issues/8728
- [x] Implement managed secret manager where the secrets inside the connection objects which are sensitive are automatically stored in the secrets manager.
  - https://github.com/open-metadata/OpenMetadata/pull/8671
  - https://github.com/open-metadata/OpenMetadata/pull/8720
  - https://github.com/open-metadata/OpenMetadata/pull/8725

**Comment by nahuelverdugo** [comment]
The pending task for reviewing the connection JSON schemas to see if any sensitive value is not being treated as a password will be handled in a separate issue.
