### ISSUE TITLE
Argo as a Pipeline Service Client

### ISSUE THREAD

**Issue by pmbrull** [open-metadata/OpenMetadata#8586]
To handle deployments of Ingestion Pipelines from the UI:

- [x] Handle SSL verification from Argo Configuration: We need to tune the `WorkflowClient.java` to manage the SSL information when connecting to the Argo Server.
    - [x] We needed prep work on OM side https://github.com/open-metadata/OpenMetadata/pull/11363
- [x] Implement all workflows: For the PoC we have worked on the metadata ingestion. We need to implement profiler, usage, lineage, test suite and data insights workflows
- [x] Get logs endpoint: We need to validate how to get logs from pods after they have run. Currently we know only how to retrieve logs from running workflows.
- [x] Implement API endpoints:
    - [x] deploy
    - [x] run
    - [x] delete
    - [x] getQueuesPipelineStatus
    - [x] toggleIngestion
    - [x] killIngestion
    - [x] requestGetHostIp -> won't implement. Keep it as env var from config
    - [x] Get logs
    - [x] Test Conection -> Pending refactor on the ingestion side. https://github.com/open-metadata/OpenMetadata/pull/10660
- [x] Add exit handler to update failed status if the workflow blows up
- [x] Add affinity from Argo Configuration: to handle in which label should pods run -> This has been handled with taints and tolerations
- [x] Local testing instructions and image version: We are now building the workflow spec with an imaged named `"openmetadata/ingestion-base:" + SERVER_VERSION`, which translates to `0.13.0-SNAPSHOT`. Validate how the tag will be built after a release, how is then the version and prepare instructions to run argo and test it with the UI locally
- [ ] Validate JWT token when deploying an Ingestion: From Argo we do not have the `ometa` client as we do from Airflow. During an Ingestion Pipeline deployment through Airflow we instantiate `ometa` and in there we are automatically validating the JWT token. Now we need to do this at the server side. Check the validity of the Ingestion Bot JWT Token and raise an error if: 
    - it does not exist
    - it is expired
    - it has an invalid signature
- [x] Handle pipelines without a schedule (`ingestionPipeline.getAirflowConfig().getScheduleInterval()` is null)
- [x] Update pipeline service client initialization as a class constructor
- [ ] Add `/validate` endpoint to the IngestionPipelineResource to check the server and client versions & check if the client can properly reach the server. Similar to what currently the airflow apis are doing during the deploy
- [ ] Handle Secret Manager configurations for Argo pods
