### ISSUE TITLE
UI/UX improvements

### ISSUE THREAD

**Issue by chirag-madlani** [open-metadata/OpenMetadata#9001]
- [x] #8170 -- @chirag-madlani 
- [ ] #9002
- [x] #9003
- [ ] #9005
- [ ] #9020
- [ ] #9021

**Comment by harshach** [comment]
- [ ] if there is no description don't show the bubble 
<img width="394" alt="image" src="https://user-images.githubusercontent.com/38649/205184018-794c6d18-b7c3-4d7e-858f-6a2dc5b818d8.png">

**Comment by ShaileshParmar11** [comment]
Lineage

- [ ] Reduce zoom default value to 0.5
- [ ] Reduce the width of edge 
- [ ] organize lineage node in better way

**Comment by harshach** [comment]
- [ ]  Please fix this font size and time duration cc @devyani-kaushik 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/205833493-4ae39aa3-8db6-41b6-bd32-737ee8486139.png">

**Comment by TeddyCr** [comment]
- [ ] profiler time or datetime value for min/max are displayed as N/A

![Screenshot 2022-12-06 at 4 26 45 PM](https://user-images.githubusercontent.com/13626425/205953275-6e082e51-bfed-4ec5-89a0-16cb1cada92a.png)

**Comment by Sachin-chaurasiya** [comment]
- [ ] Make the default filter `my data` on the landing page

![image](https://user-images.githubusercontent.com/59080942/206119430-d288fdd1-aeba-4a57-8574-7f10cdb33058.png)

**Comment by harshach** [comment]
- [ ] We are calling "Add Tag" on the left side under Tag Categories which should be "Add Tag Category" 
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/38649/206882821-f25a4116-da61-4fe3-9ebf-91e6046df6d1.png">

**Comment by TeddyCr** [comment]
- [ ] clean up summary and KPI on pages @ShaileshParmar11 
![Screenshot 2022-12-13 at 8 52 12 AM](https://user-images.githubusercontent.com/13626425/207263620-bc94caa6-0701-4c7d-849d-54b8fddb0d14.png)
![Screenshot 2022-12-13 at 8 51 21 AM](https://user-images.githubusercontent.com/13626425/207263622-4962a3af-4086-4fe1-8a38-0525bbbb3d28.png)
![Screenshot 2022-12-13 at 8 53 01 AM](https://user-images.githubusercontent.com/13626425/207263615-6f835eb1-0b59-4b57-aba9-89c41747ae47.png)

**Comment by ShaileshParmar11** [comment]
tracking pending task here -> https://github.com/open-metadata/OpenMetadata/issues/9411
